// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250617123103_AddDersToSinavOturmaPlani")]
    partial class AddDersToSinavOturmaPlani
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Donem", b =>
                {
                    b.Property<int>("DonemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonemAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DonemID");

                    b.ToTable("Donemler");

                    b.HasData(
                        new
                        {
                            DonemID = 1,
                            DonemAdi = "1. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 2,
                            DonemAdi = "1. Sınıf Bahar Dönemi"
                        },
                        new
                        {
                            DonemID = 3,
                            DonemAdi = "2. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 4,
                            DonemAdi = "2. Sınıf Bahar Dönemi"
                        },
                        new
                        {
                            DonemID = 5,
                            DonemAdi = "3. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 6,
                            DonemAdi = "3. Sınıf Bahar Dönemi"
                        },
                        new
                        {
                            DonemID = 7,
                            DonemAdi = "4. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 8,
                            DonemAdi = "4. Sınıf Bahar Dönemi"
                        });
                });

            modelBuilder.Entity("Sinif", b =>
                {
                    b.Property<int>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SinifAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SinifID");

                    b.ToTable("Siniflar");

                    b.HasData(
                        new
                        {
                            SinifID = 1,
                            SinifAdi = "1. Sınıf"
                        },
                        new
                        {
                            SinifID = 2,
                            SinifAdi = "2. Sınıf"
                        },
                        new
                        {
                            SinifID = 3,
                            SinifAdi = "3. Sınıf"
                        },
                        new
                        {
                            SinifID = 4,
                            SinifAdi = "4. Sınıf"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Ders", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DonemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kredi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OgretimElemaniID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SinifID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DersID");

                    b.HasIndex("DonemID");

                    b.HasIndex("OgretimElemaniID");

                    b.HasIndex("SinifID");

                    b.ToTable("Dersler");

                    b.HasData(
                        new
                        {
                            DersID = 1,
                            DersAdi = "Programlama II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 2,
                            DersAdi = "Matematik II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 3,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 3,
                            DersAdi = "Fizik II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 4,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 4,
                            DersAdi = "Programlama Laboratuvarı II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 5,
                            DersAdi = "Lineer Cebir",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 5,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 6,
                            DersAdi = "Web Teknolojileri",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 7,
                            DersAdi = "Kariyer Planlama ",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 8,
                            DersAdi = "Türk Dili II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 8,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 9,
                            DersAdi = "Atatürk İlkeleri ve İnkılap Tarihi II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 9,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 10,
                            DersAdi = "Atatürk İlkeleri ve İnkılap Tarihi I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 9,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 11,
                            DersAdi = "	Fizik I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 4,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 12,
                            DersAdi = "Matematik I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 3,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 13,
                            DersAdi = "Mesleki İngilizce",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 14,
                            DersAdi = "Programlama I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 15,
                            DersAdi = "Programlama Laboratuvarı I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 16,
                            DersAdi = "Türk Dili I (UE)",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 8,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 17,
                            DersAdi = "Yazılım Mühendisliğine Giriş",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 18,
                            DersAdi = "Bilgisayar Mimarisi ve Mantıksal Tasarım",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 19,
                            DersAdi = "Diferansiyel Denklemler",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 3,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 20,
                            DersAdi = "Nesneye Yönelik Programlama",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 21,
                            DersAdi = "Programlama Laboratuvarı III",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 22,
                            DersAdi = "Sayısal Analiz",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 23,
                            DersAdi = "Veri Yapıları ve Algoritmalar",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 24,
                            DersAdi = "Yazılım Gereksinimleri Analizi",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 25,
                            DersAdi = "Algoritma Analizi",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 26,
                            DersAdi = "Ayrık Matematik",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 27,
                            DersAdi = "Bilgisayar Organizasyonu",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 28,
                            DersAdi = "Olasılık ve Raslantı Değişkenleri",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 14,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 29,
                            DersAdi = "Otomata Teorisi",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 15,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 30,
                            DersAdi = "Web Programlama",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 31,
                            DersAdi = "Yazılım Mimarileri ve Tasarım",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 32,
                            DersAdi = "Java Programlama",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 33,
                            DersAdi = "Temel Afet",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 16,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 34,
                            DersAdi = "Veritabanı Yönetim Sistemleri",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 35,
                            DersAdi = "Yazılım Geliştirme-I",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 36,
                            DersAdi = "Yazılım Test ve Doğrulama",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 37,
                            DersAdi = "İşletim Sistemleri",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 38,
                            DersAdi = "Bilgi Güvenliği",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 39,
                            DersAdi = "Linux Temelleri",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 17,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 40,
                            DersAdi = "Makine Öğrenmesi Temelleri",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 41,
                            DersAdi = "	Mobil Programlama",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 18,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 42,
                            DersAdi = "Uzaktan Öğretim",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 19,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 43,
                            DersAdi = "Yazılım Geliştirme-II",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 44,
                            DersAdi = "Yazılım Proje Yönetimi",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 45,
                            DersAdi = "Oyun Programlama",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 20,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 46,
                            DersAdi = "Doğal Dil İşleme",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 47,
                            DersAdi = "Bilgisayar Grafikleri",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 48,
                            DersAdi = "Yapay Sinir Ağları",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 49,
                            DersAdi = "Yazılım Tasarımı",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 50,
                            DersAdi = "Derin Öğrenme",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 51,
                            DersAdi = "Görüntü İşleme",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 52,
                            DersAdi = "Nesnelerin İnterneti",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 53,
                            DersAdi = " Yapay Zeka ve Uzman Sistemler",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 21,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 54,
                            DersAdi = "Metin Madenciliği",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 55,
                            DersAdi = "Veri Gizleme",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 56,
                            DersAdi = "İleri Veritabanı Sistemleri",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 57,
                            DersAdi = "Robot Programlama",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 58,
                            DersAdi = " Yazılım Kalite Güvencesi",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 59,
                            DersAdi = "Kablosuz Ağlar",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 22,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 60,
                            DersAdi = "Bitirme Çalışması",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 4
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.DersProgrami", b =>
                {
                    b.Property<int>("DersProgramiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerslikID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DersProgramiID");

                    b.HasIndex("DersID");

                    b.HasIndex("DerslikID");

                    b.ToTable("DersProgramlari");

                    b.HasData(
                        new
                        {
                            DersProgramiID = 1,
                            DersID = 1,
                            DerslikID = 1,
                            Gun = "Pazartesi",
                            Saat = "10:00-11:30"
                        },
                        new
                        {
                            DersProgramiID = 2,
                            DersID = 2,
                            DerslikID = 2,
                            Gun = "Çarşamba",
                            Saat = "13:00"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Derslik", b =>
                {
                    b.Property<int>("DerslikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DerslikAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kapasite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoltukSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiraSayisi")
                        .HasColumnType("INTEGER");

                    b.HasKey("DerslikID");

                    b.ToTable("Derslikler");

                    b.HasData(
                        new
                        {
                            DerslikID = 1,
                            DerslikAdi = "Amfi",
                            Kapasite = 100,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        },
                        new
                        {
                            DerslikID = 2,
                            DerslikAdi = "Lab",
                            Kapasite = 100,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        },
                        new
                        {
                            DerslikID = 3,
                            DerslikAdi = "D-108",
                            Kapasite = 100,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        },
                        new
                        {
                            DerslikID = 4,
                            DerslikAdi = "Uzaktan Eğitim (UE)",
                            Kapasite = 300,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.KapiIsimligi", b =>
                {
                    b.Property<int>("KapiIsimligiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KapiIsimligiAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OgretimElemaniID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SinifAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("KapiIsimligiID");

                    b.HasIndex("OgretimElemaniID");

                    b.ToTable("KapiIsimlikleri");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numara")
                        .HasColumnType("TEXT");

                    b.Property<int>("RolID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SinifID")
                        .HasColumnType("INTEGER");

                    b.HasKey("KullaniciID");

                    b.HasIndex("RolID");

                    b.HasIndex("SinifID");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            KullaniciID = 2,
                            AdSoyad = "İrfan Kösesoy",
                            Eposta = "İrfan.Kosesoy@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 3,
                            AdSoyad = "Arzu Coşkun",
                            Eposta = "Arzu.Coşkun@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 4,
                            AdSoyad = "Tayfun Güray",
                            Eposta = "Tayfun.Güray@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 5,
                            AdSoyad = "Banu PAZAR",
                            Eposta = "Banu.pazar@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 6,
                            AdSoyad = "Hakan Gündüz",
                            Eposta = "Hakan.Gündüz@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 7,
                            AdSoyad = "Levent Bayındır",
                            Eposta = "Levent.Bayındır@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 8,
                            AdSoyad = "Fatma Üçler",
                            Eposta = "Fatma.Üçler@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 9,
                            AdSoyad = "Gülten Madendağ",
                            Eposta = "Gülten.Madendag@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 10,
                            AdSoyad = "Kaplan Kaplan",
                            Eposta = "Kaplan.Kaplan@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 11,
                            AdSoyad = "Zeki Konyar",
                            Eposta = "Zeki.Konyar@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 12,
                            AdSoyad = "Kerem Küçük",
                            Eposta = "Kerem.Küçük@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 13,
                            AdSoyad = "Samet Diri",
                            Eposta = "Samet.Diri@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 14,
                            AdSoyad = "Orhan Akbulut",
                            Eposta = "Orhan.Akbulut@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 15,
                            AdSoyad = "Onur Gök",
                            Eposta = "Onur.Gök@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 16,
                            AdSoyad = "İbrahim SERTÇELİK",
                            Eposta = "İbrahim.SERTÇELİK@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 17,
                            AdSoyad = "Serdar Solak",
                            Eposta = "Serdar.Solak@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 18,
                            AdSoyad = "Uğur Yıldız",
                            Eposta = "Uğur.Yıldız@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 19,
                            AdSoyad = "Yusuf Budak",
                            Eposta = "Yusuf.Budak@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 20,
                            AdSoyad = "Yavuz Selim Fatihoğlu",
                            Eposta = "Yavuz.Selim@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 21,
                            AdSoyad = "Radwan Ali Abdulghani Saleh",
                            Eposta = "Radwan.Ali@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 22,
                            AdSoyad = " Adnan Kavak",
                            Eposta = "Adnan.Kavak@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 23,
                            AdSoyad = "Ahmet Yılmaz",
                            Eposta = "ahmet.yilmaz@uni.edu",
                            Numara = "2020501234",
                            RolID = 1,
                            Sifre = "abcd1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 25,
                            AdSoyad = "Bölüm Sekreteri 1",
                            Eposta = "bolumsek@uni.edu",
                            RolID = 3,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 31,
                            AdSoyad = "Ahmet Arslan",
                            Eposta = "ahmet.arslan@uni.edu",
                            Numara = "2020501006",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 32,
                            AdSoyad = "Büşra Yılmaz",
                            Eposta = "busra.yilmaz@uni.edu",
                            Numara = "2020501007",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 33,
                            AdSoyad = "Cemil Kılıç",
                            Eposta = "cemil.kilic@uni.edu",
                            Numara = "2020501008",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 34,
                            AdSoyad = "Deniz Kaya",
                            Eposta = "deniz.kaya@uni.edu",
                            Numara = "2020501009",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 35,
                            AdSoyad = "Elif Demir",
                            Eposta = "elif.demir@uni.edu",
                            Numara = "2020501010",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 36,
                            AdSoyad = "Furkan Çelik",
                            Eposta = "furkan.celik@uni.edu",
                            Numara = "2020501011",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 37,
                            AdSoyad = "Gökhan Akbaş",
                            Eposta = "gokhan.akbas@uni.edu",
                            Numara = "2020501012",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 38,
                            AdSoyad = "Hüseyin Tekin",
                            Eposta = "huseyin.tekin@uni.edu",
                            Numara = "2020501013",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 39,
                            AdSoyad = "İsmail Erdoğan",
                            Eposta = "ismail.erdogan@uni.edu",
                            Numara = "2020501014",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 40,
                            AdSoyad = "Jale Bozkurt",
                            Eposta = "jale.bozkurt@uni.edu",
                            Numara = "2020501015",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 41,
                            AdSoyad = "Kemal Özkan",
                            Eposta = "kemal.ozkan@uni.edu",
                            Numara = "2020501016",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 42,
                            AdSoyad = "Lale Yıldız",
                            Eposta = "lale.yildiz@uni.edu",
                            Numara = "2020501017",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 43,
                            AdSoyad = "Murat Akın",
                            Eposta = "murat.akin@uni.edu",
                            Numara = "2020501018",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 44,
                            AdSoyad = "Nihan Güler",
                            Eposta = "nihan.guler@uni.edu",
                            Numara = "2020501019",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 45,
                            AdSoyad = "Ozan Aydın",
                            Eposta = "ozan.aydin@uni.edu",
                            Numara = "2020501020",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 46,
                            AdSoyad = "Pelin Çetin",
                            Eposta = "pelin.cetin@uni.edu",
                            Numara = "2020501021",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 47,
                            AdSoyad = "Rıza Demirtaş",
                            Eposta = "riza.demirtas@uni.edu",
                            Numara = "2020501022",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 48,
                            AdSoyad = "Sibel Koç",
                            Eposta = "sibel.koc@uni.edu",
                            Numara = "2020501023",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 49,
                            AdSoyad = "Tuna Kalkan",
                            Eposta = "tuna.kalkan@uni.edu",
                            Numara = "2020501024",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 50,
                            AdSoyad = "Uğur Doğan",
                            Eposta = "ugur.dogan@uni.edu",
                            Numara = "2020501025",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 53,
                            AdSoyad = "Bölüm Başkanı",
                            Eposta = "bolumbaskani@uni.edu",
                            RolID = 4,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 60,
                            AdSoyad = "Ali Yılmaz",
                            Eposta = "ali.yilmaz@uni.edu",
                            Numara = "2020501060",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 61,
                            AdSoyad = "Ayşe Demir",
                            Eposta = "ayse.demir@uni.edu",
                            Numara = "2020501061",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 62,
                            AdSoyad = "Mehmet Kara",
                            Eposta = "mehmet.kara@uni.edu",
                            Numara = "2020501062",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 63,
                            AdSoyad = "Zeynep Şahin",
                            Eposta = "zeynep.sahin@uni.edu",
                            Numara = "2020501063",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 64,
                            AdSoyad = "Emre Aydın",
                            Eposta = "emre.aydin@uni.edu",
                            Numara = "2020501064",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 65,
                            AdSoyad = "Fatma Yıldız",
                            Eposta = "fatma.yildiz@uni.edu",
                            Numara = "2020501065",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 66,
                            AdSoyad = "Ahmet Taş",
                            Eposta = "ahmet.tas@uni.edu",
                            Numara = "2020501066",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 67,
                            AdSoyad = "Elif Kurt",
                            Eposta = "elif.kurt@uni.edu",
                            Numara = "2020501067",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 68,
                            AdSoyad = "Mert Can",
                            Eposta = "mert.can@uni.edu",
                            Numara = "2020501068",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 69,
                            AdSoyad = "Buse Yalçın",
                            Eposta = "buse.yalcin@uni.edu",
                            Numara = "2020501069",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 70,
                            AdSoyad = "Oğuz Kaan",
                            Eposta = "oguz.kaan@uni.edu",
                            Numara = "2020501070",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 71,
                            AdSoyad = "Selin Polat",
                            Eposta = "selin.polat@uni.edu",
                            Numara = "2020501071",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 72,
                            AdSoyad = "Burak Güneş",
                            Eposta = "burak.gunes@uni.edu",
                            Numara = "2020501072",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 73,
                            AdSoyad = "Ceren Aksoy",
                            Eposta = "ceren.aksoy@uni.edu",
                            Numara = "2020501073",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 74,
                            AdSoyad = "Hasan Koç",
                            Eposta = "hasan.koc@uni.edu",
                            Numara = "2020501074",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 75,
                            AdSoyad = "Melis Tan",
                            Eposta = "melis.tan@uni.edu",
                            Numara = "2020501075",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 76,
                            AdSoyad = "Tuna Er",
                            Eposta = "tuna.er@uni.edu",
                            Numara = "2020501076",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 77,
                            AdSoyad = "Nazlı Gül",
                            Eposta = "nazli.gul@uni.edu",
                            Numara = "2020501077",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 78,
                            AdSoyad = "Onur Bayrak",
                            Eposta = "onur.bayrak@uni.edu",
                            Numara = "2020501078",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 79,
                            AdSoyad = "Simge Acar",
                            Eposta = "simge.acar@uni.edu",
                            Numara = "2020501079",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 80,
                            AdSoyad = "Baran Ateş",
                            Eposta = "baran.ates@uni.edu",
                            Numara = "2020501080",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 81,
                            AdSoyad = "İlayda Kılıç",
                            Eposta = "ilayda.kilic@uni.edu",
                            Numara = "2020501081",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 82,
                            AdSoyad = "Efe Demirtaş",
                            Eposta = "efe.demirtas@uni.edu",
                            Numara = "2020501082",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 83,
                            AdSoyad = "Sude Yüce",
                            Eposta = "sude.yuce@uni.edu",
                            Numara = "2020501083",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 84,
                            AdSoyad = "Kerem Bilgin",
                            Eposta = "kerem.bilgin@uni.edu",
                            Numara = "2020501084",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 85,
                            AdSoyad = "Zeliha Tuncel",
                            Eposta = "zeliha.tuncel@uni.edu",
                            Numara = "2020501085",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 86,
                            AdSoyad = "Hakan Özkan",
                            Eposta = "hakan.ozkan@uni.edu",
                            Numara = "2020501086",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 87,
                            AdSoyad = "Dilara Yılmaz",
                            Eposta = "dilara.yilmaz@uni.edu",
                            Numara = "2020501087",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 88,
                            AdSoyad = "Serkan Gültekin",
                            Eposta = "serkan.gultekin@uni.edu",
                            Numara = "2020501088",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 89,
                            AdSoyad = "Melek Şimşek",
                            Eposta = "melek.simsek@uni.edu",
                            Numara = "2020501089",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 90,
                            AdSoyad = "Enes Uçar",
                            Eposta = "enes.ucar@uni.edu",
                            Numara = "2020501090",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 91,
                            AdSoyad = "Tuğçe Kaya",
                            Eposta = "tugce.kaya@uni.edu",
                            Numara = "2020501091",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 92,
                            AdSoyad = "Yunus Emre",
                            Eposta = "yunus.emre@uni.edu",
                            Numara = "2020501092",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 93,
                            AdSoyad = "Naz Arslan",
                            Eposta = "naz.arslan@uni.edu",
                            Numara = "2020501093",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 94,
                            AdSoyad = "Berkay Gök",
                            Eposta = "berkay.gok@uni.edu",
                            Numara = "2020501094",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 95,
                            AdSoyad = "Necla Bozkurt",
                            Eposta = "necla.bozkurt@uni.edu",
                            Numara = "2020501095",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 96,
                            AdSoyad = "Taylan Ersoy",
                            Eposta = "taylan.ersoy@uni.edu",
                            Numara = "2020501096",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 97,
                            AdSoyad = "Gamze Kılıç",
                            Eposta = "gamze.kilic@uni.edu",
                            Numara = "2020501097",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 98,
                            AdSoyad = "Volkan Yalın",
                            Eposta = "volkan.yalin@uni.edu",
                            Numara = "2020501098",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 99,
                            AdSoyad = "İrem Akın",
                            Eposta = "irem.akin@uni.edu",
                            Numara = "2020501099",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 100,
                            AdSoyad = "Cansu Demirtaş",
                            Eposta = "cansu.demirtas@uni.edu",
                            Numara = "2020501100",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 101,
                            AdSoyad = "Yusuf Akman",
                            Eposta = "yusuf.akman@uni.edu",
                            Numara = "2020501101",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 102,
                            AdSoyad = "Sena Karaca",
                            Eposta = "sena.karaca@uni.edu",
                            Numara = "2020501102",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 103,
                            AdSoyad = "Kaan Erdem",
                            Eposta = "kaan.erdem@uni.edu",
                            Numara = "2020501103",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 104,
                            AdSoyad = "Merve Çetin",
                            Eposta = "merve.cetin@uni.edu",
                            Numara = "2020501104",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 105,
                            AdSoyad = "Okan Yüce",
                            Eposta = "okan.yuce@uni.edu",
                            Numara = "2020501105",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 106,
                            AdSoyad = "Beril Korkmaz",
                            Eposta = "beril.korkmaz@uni.edu",
                            Numara = "2020501106",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 107,
                            AdSoyad = "Furkan Duru",
                            Eposta = "furkan.duru@uni.edu",
                            Numara = "2020501107",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 108,
                            AdSoyad = "Gizem Uslu",
                            Eposta = "gizem.uslu@uni.edu",
                            Numara = "2020501108",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 109,
                            AdSoyad = "Ömer Faruk",
                            Eposta = "omer.faruk@uni.edu",
                            Numara = "2020501109",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 110,
                            AdSoyad = "Zehra Gök",
                            Eposta = "zehra.gok@uni.edu",
                            Numara = "2020501110",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 111,
                            AdSoyad = "Burcu Altın",
                            Eposta = "burcu.altin@uni.edu",
                            Numara = "2020501111",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 112,
                            AdSoyad = "Harun Bilgi",
                            Eposta = "harun.bilgi@uni.edu",
                            Numara = "2020501112",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 113,
                            AdSoyad = "Yasemin Tuna",
                            Eposta = "yasemin.tuna@uni.edu",
                            Numara = "2020501113",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 114,
                            AdSoyad = "Halil İbrahim",
                            Eposta = "halil.ibrahim@uni.edu",
                            Numara = "2020501114",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 115,
                            AdSoyad = "İlayda Şahin",
                            Eposta = "ilayda.sahin@uni.edu",
                            Numara = "2020501115",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 116,
                            AdSoyad = "Deniz Yaman",
                            Eposta = "deniz.yaman@uni.edu",
                            Numara = "2020501116",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 117,
                            AdSoyad = "Tunahan Erol",
                            Eposta = "tunahan.erol@uni.edu",
                            Numara = "2020501117",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 118,
                            AdSoyad = "Tuana Bal",
                            Eposta = "tuana.bal@uni.edu",
                            Numara = "2020501118",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 119,
                            AdSoyad = "Doğukan Keskin",
                            Eposta = "dogukan.keskin@uni.edu",
                            Numara = "2020501119",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 120,
                            AdSoyad = "Meltem Gür",
                            Eposta = "meltem.gur@uni.edu",
                            Numara = "2020501120",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 121,
                            AdSoyad = "Barış Kaya",
                            Eposta = "baris.kaya@uni.edu",
                            Numara = "2020501121",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 122,
                            AdSoyad = "Sibel Koç",
                            Eposta = "sibel.koc@uni.edu",
                            Numara = "2020501122",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 123,
                            AdSoyad = "Batuhan Arı",
                            Eposta = "batuhan.ari@uni.edu",
                            Numara = "2020501123",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 124,
                            AdSoyad = "Mina Dursun",
                            Eposta = "mina.dursun@uni.edu",
                            Numara = "2020501124",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 125,
                            AdSoyad = "Recep Acar",
                            Eposta = "recep.acar@uni.edu",
                            Numara = "2020501125",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 126,
                            AdSoyad = "Arda Toprak",
                            Eposta = "arda.toprak@uni.edu",
                            Numara = "2020501126",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 127,
                            AdSoyad = "Nisanur Bilge",
                            Eposta = "nisanur.bilge@uni.edu",
                            Numara = "2020501127",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 128,
                            AdSoyad = "Caner Tetik",
                            Eposta = "caner.tetik@uni.edu",
                            Numara = "2020501128",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 129,
                            AdSoyad = "Yaren Aydemir",
                            Eposta = "yaren.aydemir@uni.edu",
                            Numara = "2020501129",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolAdi = "Öğrenci"
                        },
                        new
                        {
                            RolID = 2,
                            RolAdi = "Öğretim Elemanı"
                        },
                        new
                        {
                            RolID = 3,
                            RolAdi = "Bölüm Sekreteri"
                        },
                        new
                        {
                            RolID = 4,
                            RolAdi = "Bölüm Başkanı"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Sinav", b =>
                {
                    b.Property<int>("SinavID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerslikID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgretimElemaniID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("SinavID");

                    b.HasIndex("DersID");

                    b.HasIndex("DerslikID");

                    b.HasIndex("OgretimElemaniID");

                    b.ToTable("Sinavlar");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.SinavOturmaPlani", b =>
                {
                    b.Property<int>("SinavOturmaPlaniID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerslikID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoltukNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SinifID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiraNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("SinavOturmaPlaniID");

                    b.HasIndex("DersID");

                    b.HasIndex("DerslikID");

                    b.HasIndex("OgrenciID");

                    b.HasIndex("SinifID");

                    b.ToTable("SinavOturmaPlanlari");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Ders", b =>
                {
                    b.HasOne("Donem", "Donem")
                        .WithMany("Dersler")
                        .HasForeignKey("DonemID");

                    b.HasOne("StudentManagementSystem.Data.Kullanici", "OgretimElemani")
                        .WithMany()
                        .HasForeignKey("OgretimElemaniID");

                    b.HasOne("Sinif", "Sinif")
                        .WithMany("Dersler")
                        .HasForeignKey("SinifID");

                    b.Navigation("Donem");

                    b.Navigation("OgretimElemani");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.DersProgrami", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Ders", "Ders")
                        .WithMany("DersProgramlari")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Derslik", "Derslik")
                        .WithMany("DersProgramlari")
                        .HasForeignKey("DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Derslik");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.KapiIsimligi", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Kullanici", "OgretimElemani")
                        .WithMany()
                        .HasForeignKey("OgretimElemaniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgretimElemani");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Kullanici", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sinif", "Sinif")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("SinifID");

                    b.Navigation("Rol");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Sinav", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Derslik", "Derslik")
                        .WithMany("Sinavlar")
                        .HasForeignKey("DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Kullanici", "OgretimElemani")
                        .WithMany()
                        .HasForeignKey("OgretimElemaniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Derslik");

                    b.Navigation("OgretimElemani");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.SinavOturmaPlani", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Derslik", "Derslik")
                        .WithMany()
                        .HasForeignKey("DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Derslik");

                    b.Navigation("Ogrenci");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("Donem", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("Sinif", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Ders", b =>
                {
                    b.Navigation("DersProgramlari");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Derslik", b =>
                {
                    b.Navigation("DersProgramlari");

                    b.Navigation("Sinavlar");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Rol", b =>
                {
                    b.Navigation("Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
