// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524134011_dbguncelleme3")]
    partial class dbguncelleme3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Donem", b =>
                {
                    b.Property<int>("DonemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonemAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DonemID");

                    b.ToTable("Donemler");

                    b.HasData(
                        new
                        {
                            DonemID = 1,
                            DonemAdi = "1. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 2,
                            DonemAdi = "1. Sınıf Bahar Dönemi"
                        },
                        new
                        {
                            DonemID = 3,
                            DonemAdi = "2. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 4,
                            DonemAdi = "2. Sınıf Bahar Dönemi"
                        },
                        new
                        {
                            DonemID = 5,
                            DonemAdi = "3. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 6,
                            DonemAdi = "3. Sınıf Bahar Dönemi"
                        },
                        new
                        {
                            DonemID = 7,
                            DonemAdi = "4. Sınıf Güz Dönemi"
                        },
                        new
                        {
                            DonemID = 8,
                            DonemAdi = "4. Sınıf Bahar Dönemi"
                        });
                });

            modelBuilder.Entity("Sinif", b =>
                {
                    b.Property<int>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SinifAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SinifID");

                    b.ToTable("Siniflar");

                    b.HasData(
                        new
                        {
                            SinifID = 1,
                            SinifAdi = "1. Sınıf"
                        },
                        new
                        {
                            SinifID = 2,
                            SinifAdi = "2. Sınıf"
                        },
                        new
                        {
                            SinifID = 3,
                            SinifAdi = "3. Sınıf"
                        },
                        new
                        {
                            SinifID = 4,
                            SinifAdi = "4. Sınıf"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Ders", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DonemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kredi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OgretimElemaniID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SinifID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DersID");

                    b.HasIndex("DonemID");

                    b.HasIndex("OgretimElemaniID");

                    b.HasIndex("SinifID");

                    b.ToTable("Dersler");

                    b.HasData(
                        new
                        {
                            DersID = 1,
                            DersAdi = "Programlama II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 2,
                            DersAdi = "Matematik II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 3,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 3,
                            DersAdi = "Fizik II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 4,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 4,
                            DersAdi = "Programlama Laboratuvarı II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 5,
                            DersAdi = "Lineer Cebir",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 5,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 6,
                            DersAdi = "Web Teknolojileri",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 7,
                            DersAdi = "Kariyer Planlama ",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 8,
                            DersAdi = "Türk Dili II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 8,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 9,
                            DersAdi = "Atatürk İlkeleri ve İnkılap Tarihi II",
                            DonemID = 2,
                            Kredi = 0,
                            OgretimElemaniID = 9,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 10,
                            DersAdi = "Atatürk İlkeleri ve İnkılap Tarihi I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 9,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 11,
                            DersAdi = "	Fizik I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 4,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 12,
                            DersAdi = "Matematik I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 3,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 13,
                            DersAdi = "Mesleki İngilizce",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 14,
                            DersAdi = "Programlama I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 15,
                            DersAdi = "Programlama Laboratuvarı I",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 16,
                            DersAdi = "Türk Dili I (UE)",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 8,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 17,
                            DersAdi = "Yazılım Mühendisliğine Giriş",
                            DonemID = 1,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 1
                        },
                        new
                        {
                            DersID = 18,
                            DersAdi = "Bilgisayar Mimarisi ve Mantıksal Tasarım",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 19,
                            DersAdi = "Diferansiyel Denklemler",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 3,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 20,
                            DersAdi = "Nesneye Yönelik Programlama",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 21,
                            DersAdi = "Programlama Laboratuvarı III",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 22,
                            DersAdi = "Sayısal Analiz",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 23,
                            DersAdi = "Veri Yapıları ve Algoritmalar",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 24,
                            DersAdi = "Yazılım Gereksinimleri Analizi",
                            DonemID = 3,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 25,
                            DersAdi = "Algoritma Analizi",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 26,
                            DersAdi = "Ayrık Matematik",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 27,
                            DersAdi = "Bilgisayar Organizasyonu",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 28,
                            DersAdi = "Olasılık ve Raslantı Değişkenleri",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 14,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 29,
                            DersAdi = "Otomata Teorisi",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 15,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 30,
                            DersAdi = "Web Programlama",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 31,
                            DersAdi = "Yazılım Mimarileri ve Tasarım",
                            DonemID = 4,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 2
                        },
                        new
                        {
                            DersID = 32,
                            DersAdi = "Java Programlama",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 33,
                            DersAdi = "Temel Afet",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 16,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 34,
                            DersAdi = "Veritabanı Yönetim Sistemleri",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 35,
                            DersAdi = "Yazılım Geliştirme-I",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 36,
                            DersAdi = "Yazılım Test ve Doğrulama",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 37,
                            DersAdi = "İşletim Sistemleri",
                            DonemID = 5,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 38,
                            DersAdi = "Bilgi Güvenliği",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 39,
                            DersAdi = "Linux Temelleri",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 17,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 40,
                            DersAdi = "Makine Öğrenmesi Temelleri",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 41,
                            DersAdi = "	Mobil Programlama",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 18,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 42,
                            DersAdi = "Uzaktan Öğretim",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 19,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 43,
                            DersAdi = "Yazılım Geliştirme-II",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 44,
                            DersAdi = "Yazılım Proje Yönetimi",
                            DonemID = 6,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 3
                        },
                        new
                        {
                            DersID = 45,
                            DersAdi = "Oyun Programlama",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 20,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 46,
                            DersAdi = "Doğal Dil İşleme",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 6,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 47,
                            DersAdi = "Bilgisayar Grafikleri",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 48,
                            DersAdi = "Yapay Sinir Ağları",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 10,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 49,
                            DersAdi = "Yazılım Tasarımı",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 50,
                            DersAdi = "Derin Öğrenme",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 51,
                            DersAdi = "Görüntü İşleme",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 52,
                            DersAdi = "Nesnelerin İnterneti",
                            DonemID = 7,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 53,
                            DersAdi = " Yapay Zeka ve Uzman Sistemler",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 21,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 54,
                            DersAdi = "Metin Madenciliği",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 2,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 55,
                            DersAdi = "Veri Gizleme",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 11,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 56,
                            DersAdi = "İleri Veritabanı Sistemleri",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 13,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 57,
                            DersAdi = "Robot Programlama",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 7,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 58,
                            DersAdi = " Yazılım Kalite Güvencesi",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 59,
                            DersAdi = "Kablosuz Ağlar",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 22,
                            SinifID = 4
                        },
                        new
                        {
                            DersID = 60,
                            DersAdi = "Bitirme Çalışması",
                            DonemID = 8,
                            Kredi = 0,
                            OgretimElemaniID = 12,
                            SinifID = 4
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.DersProgrami", b =>
                {
                    b.Property<int>("DersProgramiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerslikID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DersProgramiID");

                    b.HasIndex("DersID");

                    b.HasIndex("DerslikID");

                    b.ToTable("DersProgramlari");

                    b.HasData(
                        new
                        {
                            DersProgramiID = 1,
                            DersID = 1,
                            DerslikID = 1,
                            Gun = "Pazartesi",
                            Saat = "10:00-11:30"
                        },
                        new
                        {
                            DersProgramiID = 2,
                            DersID = 2,
                            DerslikID = 2,
                            Gun = "Çarşamba",
                            Saat = "13:00"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Derslik", b =>
                {
                    b.Property<int>("DerslikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DerslikAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kapasite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoltukSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiraSayisi")
                        .HasColumnType("INTEGER");

                    b.HasKey("DerslikID");

                    b.ToTable("Derslikler");

                    b.HasData(
                        new
                        {
                            DerslikID = 1,
                            DerslikAdi = "Amfi",
                            Kapasite = 100,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        },
                        new
                        {
                            DerslikID = 2,
                            DerslikAdi = "Lab",
                            Kapasite = 100,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        },
                        new
                        {
                            DerslikID = 3,
                            DerslikAdi = "D-108",
                            Kapasite = 100,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        },
                        new
                        {
                            DerslikID = 4,
                            DerslikAdi = "Uzaktan Eğitim (UE)",
                            Kapasite = 300,
                            KoltukSayisi = 0,
                            SiraSayisi = 0
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.KapiIsimligi", b =>
                {
                    b.Property<int>("KapiIsimligiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KapiIsimligiAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OgretimElemaniID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SinifAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("KapiIsimligiID");

                    b.HasIndex("OgretimElemaniID");

                    b.ToTable("KapiIsimlikleri");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numara")
                        .HasColumnType("TEXT");

                    b.Property<int>("RolID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SinifID")
                        .HasColumnType("INTEGER");

                    b.HasKey("KullaniciID");

                    b.HasIndex("RolID");

                    b.HasIndex("SinifID");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            KullaniciID = 2,
                            AdSoyad = "İrfan Kösesoy",
                            Eposta = "İrfan.Kosesoy@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 3,
                            AdSoyad = "Arzu Coşkun",
                            Eposta = "Arzu.Coşkun@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 4,
                            AdSoyad = "Tayfun Güray",
                            Eposta = "Tayfun.Güray@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 5,
                            AdSoyad = "Banu PAZAR",
                            Eposta = "Banu.pazar@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 6,
                            AdSoyad = "Hakan Gündüz",
                            Eposta = "Hakan.Gündüz@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 7,
                            AdSoyad = "Levent Bayındır",
                            Eposta = "Levent.Bayındır@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 8,
                            AdSoyad = "Fatma Üçler",
                            Eposta = "Fatma.Üçler@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 9,
                            AdSoyad = "Gülten Madendağ",
                            Eposta = "Gülten.Madendag@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 10,
                            AdSoyad = "Kaplan Kaplan",
                            Eposta = "Kaplan.Kaplan@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 11,
                            AdSoyad = "Zeki Konyar",
                            Eposta = "Zeki.Konyar@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 12,
                            AdSoyad = "Kerem Küçük",
                            Eposta = "Kerem.Küçük@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 13,
                            AdSoyad = "Samet Diri",
                            Eposta = "Samet.Diri@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 14,
                            AdSoyad = "Orhan Akbulut",
                            Eposta = "Orhan.Akbulut@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 15,
                            AdSoyad = "Onur Gök",
                            Eposta = "Onur.Gök@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 16,
                            AdSoyad = "İbrahim SERTÇELİK",
                            Eposta = "İbrahim.SERTÇELİK@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 17,
                            AdSoyad = "Serdar Solak",
                            Eposta = "Serdar.Solak@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 18,
                            AdSoyad = "Uğur Yıldız",
                            Eposta = "Uğur.Yıldız@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 19,
                            AdSoyad = "Yusuf Budak",
                            Eposta = "Yusuf.Budak@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 20,
                            AdSoyad = "Yavuz Selim Fatihoğlu",
                            Eposta = "Yavuz.Selim@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 21,
                            AdSoyad = "Radwan Ali Abdulghani Saleh",
                            Eposta = "Radwan.Ali@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 22,
                            AdSoyad = " Adnan Kavak",
                            Eposta = "Adnan.Kavak@uni.edu",
                            RolID = 2,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 23,
                            AdSoyad = "Ahmet Yılmaz",
                            Eposta = "ahmet.yilmaz@uni.edu",
                            Numara = "2020501234",
                            RolID = 1,
                            Sifre = "abcd1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 25,
                            AdSoyad = "Bölüm Sekreteri 1",
                            Eposta = "bolumsek@uni.edu",
                            RolID = 3,
                            Sifre = "1234"
                        },
                        new
                        {
                            KullaniciID = 31,
                            AdSoyad = "Ahmet Arslan",
                            Eposta = "ahmet.arslan@uni.edu",
                            Numara = "2020501006",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 32,
                            AdSoyad = "Büşra Yılmaz",
                            Eposta = "busra.yilmaz@uni.edu",
                            Numara = "2020501007",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 33,
                            AdSoyad = "Cemil Kılıç",
                            Eposta = "cemil.kilic@uni.edu",
                            Numara = "2020501008",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 34,
                            AdSoyad = "Deniz Kaya",
                            Eposta = "deniz.kaya@uni.edu",
                            Numara = "2020501009",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 35,
                            AdSoyad = "Elif Demir",
                            Eposta = "elif.demir@uni.edu",
                            Numara = "2020501010",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 36,
                            AdSoyad = "Furkan Çelik",
                            Eposta = "furkan.celik@uni.edu",
                            Numara = "2020501011",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 37,
                            AdSoyad = "Gökhan Akbaş",
                            Eposta = "gokhan.akbas@uni.edu",
                            Numara = "2020501012",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 38,
                            AdSoyad = "Hüseyin Tekin",
                            Eposta = "huseyin.tekin@uni.edu",
                            Numara = "2020501013",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 39,
                            AdSoyad = "İsmail Erdoğan",
                            Eposta = "ismail.erdogan@uni.edu",
                            Numara = "2020501014",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 40,
                            AdSoyad = "Jale Bozkurt",
                            Eposta = "jale.bozkurt@uni.edu",
                            Numara = "2020501015",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 41,
                            AdSoyad = "Kemal Özkan",
                            Eposta = "kemal.ozkan@uni.edu",
                            Numara = "2020501016",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 42,
                            AdSoyad = "Lale Yıldız",
                            Eposta = "lale.yildiz@uni.edu",
                            Numara = "2020501017",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 43,
                            AdSoyad = "Murat Akın",
                            Eposta = "murat.akin@uni.edu",
                            Numara = "2020501018",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 44,
                            AdSoyad = "Nihan Güler",
                            Eposta = "nihan.guler@uni.edu",
                            Numara = "2020501019",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 45,
                            AdSoyad = "Ozan Aydın",
                            Eposta = "ozan.aydin@uni.edu",
                            Numara = "2020501020",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 46,
                            AdSoyad = "Pelin Çetin",
                            Eposta = "pelin.cetin@uni.edu",
                            Numara = "2020501021",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 47,
                            AdSoyad = "Rıza Demirtaş",
                            Eposta = "riza.demirtas@uni.edu",
                            Numara = "2020501022",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 48,
                            AdSoyad = "Sibel Koç",
                            Eposta = "sibel.koc@uni.edu",
                            Numara = "2020501023",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 49,
                            AdSoyad = "Tuna Kalkan",
                            Eposta = "tuna.kalkan@uni.edu",
                            Numara = "2020501024",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 50,
                            AdSoyad = "Uğur Doğan",
                            Eposta = "ugur.dogan@uni.edu",
                            Numara = "2020501025",
                            RolID = 1,
                            Sifre = "1234",
                            SinifID = 1
                        },
                        new
                        {
                            KullaniciID = 53,
                            AdSoyad = "Bölüm Başkanı",
                            Eposta = "bolumbaskani@uni.edu",
                            RolID = 4,
                            Sifre = "1234"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolAdi = "Öğrenci"
                        },
                        new
                        {
                            RolID = 2,
                            RolAdi = "Öğretim Elemanı"
                        },
                        new
                        {
                            RolID = 3,
                            RolAdi = "Bölüm Sekreteri"
                        },
                        new
                        {
                            RolID = 4,
                            RolAdi = "Bölüm Başkanı"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Sinav", b =>
                {
                    b.Property<int>("SinavID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerslikID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgretimElemaniID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("SinavID");

                    b.HasIndex("DersID");

                    b.HasIndex("DerslikID");

                    b.HasIndex("OgretimElemaniID");

                    b.ToTable("Sinavlar");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.SinavOturmaPlani", b =>
                {
                    b.Property<int>("SinavOturmaPlaniID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerslikID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoltukNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SinifID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiraNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("SinavOturmaPlaniID");

                    b.HasIndex("DerslikID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("SinavOturmaPlanlari");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Ders", b =>
                {
                    b.HasOne("Donem", "Donem")
                        .WithMany("Dersler")
                        .HasForeignKey("DonemID");

                    b.HasOne("StudentManagementSystem.Data.Kullanici", "OgretimElemani")
                        .WithMany()
                        .HasForeignKey("OgretimElemaniID");

                    b.HasOne("Sinif", "Sinif")
                        .WithMany("Dersler")
                        .HasForeignKey("SinifID");

                    b.Navigation("Donem");

                    b.Navigation("OgretimElemani");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.DersProgrami", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Ders", "Ders")
                        .WithMany("DersProgramlari")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Derslik", "Derslik")
                        .WithMany("DersProgramlari")
                        .HasForeignKey("DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Derslik");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.KapiIsimligi", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Kullanici", "OgretimElemani")
                        .WithMany()
                        .HasForeignKey("OgretimElemaniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgretimElemani");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Kullanici", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sinif", "Sinif")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("SinifID");

                    b.Navigation("Rol");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Sinav", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Derslik", "Derslik")
                        .WithMany("Sinavlar")
                        .HasForeignKey("DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Kullanici", "OgretimElemani")
                        .WithMany()
                        .HasForeignKey("OgretimElemaniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Derslik");

                    b.Navigation("OgretimElemani");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.SinavOturmaPlani", b =>
                {
                    b.HasOne("StudentManagementSystem.Data.Derslik", "Derslik")
                        .WithMany()
                        .HasForeignKey("DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Data.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Derslik");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Donem", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("Sinif", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Ders", b =>
                {
                    b.Navigation("DersProgramlari");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Derslik", b =>
                {
                    b.Navigation("DersProgramlari");

                    b.Navigation("Sinavlar");
                });

            modelBuilder.Entity("StudentManagementSystem.Data.Rol", b =>
                {
                    b.Navigation("Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
